# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MutchRecordApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MutchRecordApp
  pod 'Charts'

  target 'MutchRecordAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MutchRecordAppUITests' do
    # Pods for testing
  end

end
